In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [85]:
df=pd.read_csv('weather.csv')

In [86]:
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,11-01-2007,Canberra,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,11-02-2007,Canberra,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,11-03-2007,Canberra,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,11-04-2007,Canberra,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,11-05-2007,Canberra,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [87]:
new_data = df[['MaxTemp', 'Rainfall','Humidity3pm','Cloud9am','RISK_MM']]

In [88]:
new_data

     MaxTemp  Rainfall  Humidity3pm  Cloud9am  RISK_MM
0       24.3       0.0           29         7      3.6
1       26.9       3.6           36         5      3.6
2       23.4       3.6           69         8     39.8
3       15.5      39.8           56         2      2.8
4       16.1       2.8           49         7      0.0
5       16.9       0.0           57         7      0.2
6       18.2       0.2           47         4      0.0
7       17.0       0.0           57         6      0.0
8       19.5       0.0           48         7     16.2
9       22.8      16.2           32         7      0.0
10      25.2       0.0           34         1      0.2
11      27.3       0.2           35         0      0.0
12      27.9       0.0           29         0      0.0
13      30.9       0.0           20         1      0.0
14      31.2       0.0           16         0      0.0
15      32.1       0.0           22         0      0.0
16      31.2       0.0           23         7      1.2
17      30.0       1.2           26         1      0.6
18      32.3       0.6           25         1      0.0
19      33.4       0.0           27         0      0.0
20      33.4       0.0           26         1      0.4
21      19.4       0.4           72         8     25.8
22      18.5      25.8           79         8      0.4
23      24.3       0.4           57         7      0.0
24      28.4       0.0           31         8      0.0
25      26.9       0.0           48         2      0.2
26      22.2       0.2           55         7      0.0
27      28.0       0.0           31         5      0.0
28      24.3       0.0           80         7      0.4
29      24.1       0.4           49         8     22.6
..       ...       ...          ...       ...      ...
336     27.6       0.0           21         0      0.0
337     28.9       0.0           22         1      7.6
338     20.7       7.6           65         8      3.0
339     21.3       3.0           46         8      0.0
340     18.0       0.0           40         5      8.2
341     16.0       8.2           45         1      0.0
342     17.9       0.0           33         0      0.0
343     20.0       0.0           22         0      0.0
344     22.0       0.0           25         1      0.0
345     22.4       0.0           30         1      0.0
346     23.9       0.0           27         0      0.0
347     26.1       0.0           47         4     13.2
348     21.1      13.2           61         7      0.6
349     19.6       0.6           42         7      0.0
350     21.0       0.0           30         1      0.0
351     24.1       0.0           34         6      0.0
352     24.7       0.0           31         1      0.0
353     28.5       0.0           30         1      0.2
354     27.4       0.2           20         1      0.0
355     20.6       0.0           28         7      0.8
356     15.0       0.8           24         1      0.0
357     18.0       0.0           25         1      0.0
358     20.7       0.0           29         3      0.0
359     25.5       0.0           16         0      0.0
360     26.1       0.0           20         5      0.0
361     30.7       0.0           15         1      0.0
362     28.4       0.0           22         0      0.0
363     19.9       0.0           47         3      0.0
364     26.9       0.0           39         6      0.0
365     30.2       0.0           13         1      0.0

[366 rows x 5 columns]

In [89]:
new_data.head()

   MaxTemp  Rainfall  Humidity3pm  Cloud9am  RISK_MM
0     24.3       0.0           29         7      3.6
1     26.9       3.6           36         5      3.6
2     23.4       3.6           69         8     39.8
3     15.5      39.8           56         2      2.8
4     16.1       2.8           49         7      0.0

In [90]:
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
data=new_data.values

def norm(x):
    min_max_scaler=MinMaxScaler()
    X_scaled=min_max_scaler.fit_transform(x)
    return X_scaled

x=data[:, 0:4]
y=data[:,4]
y=pd.Series(np.where(y == 'Yes', 1, 0),y)

x = norm(x)
y = norm(y.reshape(-1,1))
print(y)

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]

/home/aswinrprasad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  del sys.path[0]
/home/aswinrprasad/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  app.launch_new_instance()
/home/aswinrprasad/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

In [91]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

In [92]:
x_train

array([[ 0.64893617,  0.        ,  0.26506024,  0.75      ],
       [ 0.02836879,  0.04020101,  0.63855422,  0.875     ],
       [ 0.5248227 ,  0.        ,  0.20481928,  0.125     ],
       ...,
       [ 0.83687943,  0.        ,  0.03614458,  0.        ],
       [ 0.42553191,  0.47236181,  0.90361446,  1.        ],
       [ 0.60638298,  0.        ,  0.21686747,  0.125     ]])

In [93]:
y_test

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [94]:
x_train.shape

(292, 4)

In [95]:
x_test.shape

(74, 4)

In [96]:
y_train.shape

(292, 1)

In [97]:
y_test.shape

(74, 1)

In [98]:
def cost(x,theta,y):
    temp1 = (np.dot(x,theta)-y).reshape(1,len(x[:,0]))
    cost = []
    for p in range(len(theta)):
        tempx = x[:,p]
        temp2 = np.dot(temp1,tempx)
        tempsum = temp2.sum()
        cost.append(tempsum/(len(y)))
    return np.array(cost)


def gradient_descent(alpha, x,y,norma,max_iter=1500):
    if(norma==True):
        x = norm(x.reshape(-1,1))
        y = norm(y.reshape(-1,1))
    theta = np.random.rand(x.shape[1]+1,1)
    temp = np.ones(len(x))
    y = np.array(y)
    x = np.vstack((temp.T,x.T)).T
    y = y.reshape(len(y),1)
    for i in range(max_iter):
        costval = cost(x,theta,y)
        for j in range(x.shape[1]):
            theta[j] -=alpha*costval[j]
    return theta

In [111]:
#theta = gradient_descent(0.001, x_train, y_train,False)

292

In [100]:
temp = np.ones(len(x_test))
x_test = np.vstack((temp.T, x_test.T))
y_pred = np.dot(x_test.T, theta)
mse = (1/(len(x_test))) * np.square(y_pred-y_test).sum()
print("Mean squared error",mse)

Mean squared error 0.494894191575

In [101]:
theta

array([[-0.15569094],
       [-0.09358343],
       [ 0.07629888],
       [ 0.40932206],
       [ 0.23443069]])